### ISSUE TITLE
Make 0.1.0 release before tutorials

### ISSUE THREAD

**Issue by moorepants** [pydy/pydy-viz#96]
We'd like to get the release out mid to mid-late feb, see milestone.

**Comment by tarzzz** [comment]
Things to complete for 0.1.0 release ...
- [x] dependency specification in setup.py. Issue #79 PR #106
- [x] merging in new stable UI. PR #103
- [ ] Fixing camera zoom option(using THREE's boundingbox property). This is not highest priority. Issue #104
- [x] Figure out Issue #105 PR #107
- [x] Push docs to readthedocs.
- [x] Push code to PyPI

**Comment by moorepants** [comment]
See issues marked in 0.1.0 milestone:
https://github.com/pydy/pydy-viz/issues?milestone=1&page=1&state=open

**Comment by moorepants** [comment]
Here are some basic release steps to get this onto PyPi:

https://github.com/csu-hmc/Gait-Analysis-Toolkit/blob/master/RELEASE.txt

**Comment by tarzzz** [comment]
Is that text still not showing on your local master?
This is what I get when I run visualization notebook ...

**Comment by moorepants** [comment]
Yes, I am running the master branch.

**Comment by moorepants** [comment]
Released.
